export const FETCH_ALL_BATTLE = 'FETCH_ALL_BATTLE';
export const FETCH_FILTERED_BATTLE = 'FETCH_FILTERED_BATTLE';
export const FETCH_ALL_PLACES = 'FETCH_ALL_PLACES';
export const FETCH_ALL_PLACES_START_WITH = 'FETCH_ALL_PLACES_START_WITH';
export const EMPTY_FILTERED_LOCATIONS = 'EMPTY_FILTERED_LOCATIONS';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
